//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Herramientas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodoTicket
    {
        public PeriodoTicket()
        {
            this.TipoTicket = new HashSet<TipoTicket>();
        }
    
        public int IdPeriodoTicket { get; set; }
        public string Periodo { get; set; }
        public string Rango { get; set; }
        public Nullable<short> Estado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual ICollection<TipoTicket> TipoTicket { get; set; }
    }
}
