//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Herramientas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.UsuarioTicket = new HashSet<UsuarioTicket>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdTipo { get; set; }
        public string Ticket1 { get; set; }
        public bool Activo { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<short> Estado { get; set; }
        public Nullable<bool> Notificado { get; set; }
    
        public virtual ICollection<UsuarioTicket> UsuarioTicket { get; set; }
        public virtual TipoTicket TipoTicket { get; set; }
    }
}
