//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Herramientas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoTicket
    {
        public TipoTicket()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int IdTipoTicket { get; set; }
        public int IdPeriodoTicket { get; set; }
        public string NombreTipoTicket { get; set; }
        public int Cuota { get; set; }
        public Nullable<short> Estado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual PeriodoTicket PeriodoTicket { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
