//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Herramientas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.UsuarioTicket = new HashSet<UsuarioTicket>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Codigo { get; set; }
        public int IdTipo { get; set; }
        public int Rut { get; set; }
        public string Dv { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Fono { get; set; }
        public string Email { get; set; }
        public int Genero { get; set; }
        public string Empresa { get; set; }
        public string Descripcion { get; set; }
        public int Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual TipoUsuario TipoUsuario { get; set; }
        public virtual ICollection<UsuarioTicket> UsuarioTicket { get; set; }
    }
}
