//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Herramientas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioTicket
    {
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public int IdTicket { get; set; }
        public string Observaciones { get; set; }
        public string Sugerencias { get; set; }
        public Nullable<short> Estado { get; set; }
        public Nullable<System.DateTime> FechaAsignacion { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
